language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.3.4
    - DJANGO_VERSION=1.4.2
before_install:
    - export DJANGO_SETTINGS_MODULE=data_exports.test_settings
install:
    - pip install Django==$DJANGO_VERSION
    - pip install -r test_requirements.txt
    - pip install -e .
script:
    - django-admin.py test data_exports
