language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6
install:
  - pip install flake8 Django==$DJANGO_VERSION
  - pip install -e .
script:
  - django-admin.py test --settings=data_exports.test_settings data_exports
  - flake8 data_exports --exclude=migrations/
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.3.7
    - python: "3.3"
      env: DJANGO_VERSION=1.4.10
